[package]
name = "gardm-greeter"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "gar display manager greeter"

[[bin]]
name = "gardm-greeter"
path = "src/main.rs"

[[bin]]
name = "test-auth"
path = "src/bin/test-auth.rs"

[dependencies]
gardm-ipc = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
rpassword = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
nix = { workspace = true }
shellexpand = { workspace = true }

# X11 and graphics
x11rb = { workspace = true }
cairo-rs = { workspace = true }
pango = { workspace = true }
pangocairo = { workspace = true }
image = { workspace = true }
